In [46]:
# Import required libraries
import pandas as pd
import numpy as np

In [47]:
# Load Titanic dataset
df = pd.read_csv("titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas",female,14.0,1,0,237736,30.0708,NaN,C

In [48]:
# Display dataset
print("Original Dataset:")
print(df.head())

Original Dataset:
   PassengerId  Survived  Pclass                          Name     Sex   Age  \
0            1         0       3       Braund, Mr. Owen Harris    male  22.0
1            2         1       1    Cumings, Mrs. John Bradley  female  38.0
2            3         1       3        Heikkinen, Miss. Laina  female  26.0
3            4         1       1  Futrelle, Mrs. Jacques Heath  female  35.0
4            5         0       3      Allen, Mr. William Henry    male  35.0

   SibSp  Parch            Ticket     Fare Cabin Embarked
0      1      0         A/5 21171   7.2500   NaN        S
1      1      0          PC 17599  71.2833   C85        C
2      0      0  STON/O2. 3101282   7.9250   NaN        S
3      1      0            113803  53.1000  C123        S
4      0      0            373450   8.0500   NaN        S

In [49]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [50]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

1. Explore the Columns

The Titanic dataset contains various columns that describe the details of passengers. The PassengerId is a generated unique identification number for each passenger. The Survived column represents whether a passenger survived or not, where 0 indicates not survived and 1 indicates survived. The Pclass refers to the ticket class of the passenger. The Name column stores the name of the passenger, while Sex indicates whether the passenger is male or female. The Age column shows the age of the passenger. The SibSp column represents the number of siblings or spouses accompanying the passenger, and Parch represents the number of parents or children with the passenger. The Ticket column contains the ticket number, and Fare shows the ticket price. The Cabin column represents the cabin number, and Embarked indicates the port from which the passenger boarded the ship.

In [51]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [52]:
print("Total number of passengers in the training data..", len(df))
print("Number of passengers who survived..", len(df[df['Survived'] == 1]))
print("Number of passengers who didn't survived..", len(df[df['Survived'] == 0]))

Total number of passengers in the training data.. 10
Number of passengers who survived.. 5
Number of passengers who didn't survived.. 5

In [53]:
df['Sex'].value_counts()

Sex
male      5
female    5
Name: count, dtype: int64

In [54]:
print("% of male who survived", 100*np.mean(df['Survived'][df['Sex'] == 'male']))
print("% of female who survived", 100*np.mean(df['Survived'][df['Sex'] == 'female']))

% of male who survived 0.0
% of female who survived 100.0

In [55]:
df['Pclass'].value_counts()

Pclass
3    6
1    3
2    1
Name: count, dtype: int64

In [56]:
print("% of passengers who survived in first class",
      100*np.mean(df['Survived'][df['Pclass'] == 1]))

print("% of passengers who survived in second class",
      100*np.mean(df['Survived'][df['Pclass'] == 2]))

print("% of passengers who survived in third class",
      100*np.mean(df['Survived'][df['Pclass'] == 3]))

% of passengers who survived in first class 66.66666666666666
% of passengers who survived in second class 100.0
% of passengers who survived in third class 33.33333333333333

In [57]:
df[['Pclass', 'Survived']].groupby(['Pclass'], as_index=False).mean()

   Pclass  Survived
0       1  0.666667
1       2  1.000000
2       3  0.333333

2.Summary

In [58]:
df.shape

(10, 12)

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  10 non-null     int64
 1   Survived     10 non-null     int64
 2   Pclass       10 non-null     int64
 3   Name         10 non-null     object
 4   Sex          10 non-null     object
 5   Age          9 non-null      float64
 6   SibSp        10 non-null     int64
 7   Parch        10 non-null     int64
 8   Ticket       10 non-null     object
 9   Fare         10 non-null     float64
 10  Cabin        3 non-null      object
 11  Embarked     10 non-null     object
dtypes: float64(2), int64(5), object(5)
memory usage: 1.1+ KB

In [60]:
df['Age'].value_counts()

Age
35.0    2
22.0    1
38.0    1
26.0    1
54.0    1
2.0     1
27.0    1
14.0    1
Name: count, dtype: int64

In [61]:
df['Cabin']

0     NaN
1     C85
2     NaN
3    C123
4     NaN
5     NaN
6     E46
7     NaN
8     NaN
9     NaN
Name: Cabin, dtype: object

In [62]:
df['Sex']

0      male
1    female
2    female
3    female
4      male
5      male
6      male
7      male
8    female
9    female
Name: Sex, dtype: object

In [63]:
df2=df.copy()
df2['Sex']=df['Sex'].apply(lambda x: 1 if x=='male'else 0)
df2['Sex']

0    1
1    0
2    0
3    0
4    1
5    1
6    1
7    1
8    0
9    0
Name: Sex, dtype: int64

In [64]:
def fun(x):
    if x=='male':return 1
    else:return 0

3.Dealing with Missing Values

In [65]:
df2=df.copy()
df2.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            1
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          7
Embarked       0
dtype: int64

In [66]:
int(df['Age'].mean())

28

In [67]:
df2['Age']=df2['Age'].fillna(np.mean(df2['Age']))
df2.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          7
Embarked       0
dtype: int64

In [68]:
df2.Embarked.value_counts()

Embarked
S    7
C    2
Q    1
Name: count, dtype: int64

In [69]:
emabark=df2['Embarked'].isnull()

In [70]:
df2[df2['Embarked'].isnull()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [71]:
df2.Embarked.mode()

0    S
Name: Embarked, dtype: object

In [72]:
df2['Embarked'].fillna(df2['Embarked'].mode()[0], inplace=True)

C:\Users\Shree\AppData\Local\Temp\ipykernel_24424\1512377307.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['Embarked'].fillna(df2['Embarked'].mode()[0], inplace=True)

In [73]:
df2.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          7
Embarked       0
dtype: int64

In [74]:
# Count values in Cabin column
df2['Cabin'].value_counts()

Cabin
C85     1
C123    1
E46     1
Name: count, dtype: int64

In [75]:
df2['Cabin'].mode()

0    C123
1     C85
2     E46
Name: Cabin, dtype: object

In [76]:
df['Cabin'].value_counts()
df['Cabin'].mode()

0    C123
1     C85
2     E46
Name: Cabin, dtype: object

In [77]:
df2['PassengerId'].corr(df2['Pclass'])

np.float64(0.09670980886427658)